### ISSUE TITLE
compile error - incompatible pointer type

### ISSUE THREAD

**Issue by espencer127** [lwfinger/rtl8192ee#37]
I'm facing many warnings and one error when running `make all` -

```
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:424:6: warning: no previous prototype for ‘rtw_2g_channels_init’ [-Wmissing-prototypes]
  424 | void rtw_2g_channels_init(struct ieee80211_channel *channels)
      |      ^~~~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:429:6: warning: no previous prototype for ‘rtw_5g_channels_init’ [-Wmissing-prototypes]
  429 | void rtw_5g_channels_init(struct ieee80211_channel *channels)
      |      ^~~~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:434:6: warning: no previous prototype for ‘rtw_2g_rates_init’ [-Wmissing-prototypes]
  434 | void rtw_2g_rates_init(struct ieee80211_rate *rates)
      |      ^~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:441:6: warning: no previous prototype for ‘rtw_5g_rates_init’ [-Wmissing-prototypes]
  441 | void rtw_5g_rates_init(struct ieee80211_rate *rates)
      |      ^~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:448:34: warning: no previous prototype for ‘rtw_spt_band_alloc’ [-Wmissing-prototypes]
  448 | struct ieee80211_supported_band *rtw_spt_band_alloc(
      |                                  ^~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:493:6: warning: no previous prototype for ‘rtw_spt_band_free’ [-Wmissing-prototypes]
  493 | void rtw_spt_band_free(struct ieee80211_supported_band *spt_band)
      |      ^~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:2259:5: warning: no previous prototype for ‘rtw_cfg80211_is_target_wps_scan’ [-Wmissing-prototypes]
 2259 | int rtw_cfg80211_is_target_wps_scan(struct cfg80211_scan_request *scan_req, struct cfg80211_ssid *target_ssid)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:4685:18: warning: no previous prototype for ‘rtw_sta_info_get_by_idx’ [-Wmissing-prototypes]
 4685 | struct sta_info *rtw_sta_info_get_by_idx(const int idx, struct sta_priv *pstapriv)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:7346:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
 7346 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.c:7346:26: note: (near initialization for ‘rtw_cfg80211_ops.change_beacon’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /opt/rtl18192ee/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-40-generic/Makefile:1926: /opt/rtl18192ee] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-40-generic'
make: *** [Makefile:1827: modules] Error 2
```

This looks the same as an issue on another repo, [link](https://github.com/lwfinger/rtl8723bu/issues/200)

**Comment by trendschau** [comment]
I am having the same problem with Kernel: 6.8.0-41-generic

**Comment by djkib** [comment]
I am using "sudo make all" to build on Kernel 6.8.0-40-generic. I am also having this same build issue - relevant part from make output:

/home/keith/rtl8192ee/os_dep/linux/ioctl_cfg80211.c:7346:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
 7346 |         .change_beacon = cfg80211_rtw_change_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/keith/rtl8192ee/os_dep/linux/ioctl_cfg80211.c:7346:26: note: (near initialization for ‘rtw_cfg80211_ops.change_beacon’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/keith/rtl8192ee/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-40-generic/Makefile:1926: /home/keith/rtl8192ee] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-40-generic'
make: *** [Makefile:1827: modules] Error 2

**Comment by ssmns** [comment]
Same Issue: #39
