### PR TITLE
Fix for compilation errors on Linux 6.8

### PR DESCRIPTION
**Pull request by Zorono**
Fix for #40

### CODE REVIEW

**Review by LiohMoeller — COMMENTED** [review]
I can confirm that the patch works on Kernel 6.8.9

**Comment by BlueStaggo** [comment]
Hey @Zorono, do you think you could get this updated for Linux 6.13? I am dissatisfied with the state of the base kernel implementation so it would be nice to get this driver updated. Would be even better if we could get a proper maintainer for this stuff.

**Comment by Zorono** [comment]
> Hey @Zorono, do you think you could get this updated for Linux 6.13? I am dissatisfied with the state of the base kernel implementation so it would be nice to get this driver updated. Would be even better if we could get a proper maintainer for this stuff.

i don't have free time these days so i have to postpone this project
